### ISSUE TITLE
DW Optimizer/Task 2/Step 4

### ISSUE THREAD

**Issue by anshul82-ms** [solliancenet/azure-synapse-analytics-workshop-400#25]
The complex query is throwing an error:
SELECT 
    AVG(TotalProfit) as AvgMonthlyCustomerProfit
FROM
(
    SELECT
        S.CustomerId
        ,D.Year
        ,D.Month
        ,SUM(S.TotalAmount) as TotalAmount
        ,AVG(S.TotalAmount) as AvgAmount
        ,SUM(S.ProfitAmount) as TotalProfit
        ,AVG(S.ProfitAmount) as AvgProfit
    FROM
        [wwi_perf].[Sale_Partition01] S
        join [wwi].[Date] D on 
            D.DateId = S.TransactionDateId
    WHERE
        D.Year in (2010, 2011, 2012, 2013, 2014)
    GROUP BY
        S.CustomerId
        ,D.Year
        ,D.Month
) T

**Comment by ciprianjichici** [comment]
Can you please provide more details, we are unable to reproduce. 

![image](https://user-images.githubusercontent.com/3429726/80646180-f0434000-8a74-11ea-82a9-8dae466a2beb.png)

**Comment by givenscj** [comment]
Ran this lab, all queries execute ok.
