### ISSUE TITLE
Lab 2 / Exercise 4 / Step 8

### ISSUE THREAD

**Issue by periclesrocha** [solliancenet/azure-synapse-analytics-workshop-400#29]
Maybe because I'm getting much less data (see previous issue I logged), from this step forward, I'm not getting any rows in the queries

Step 8: 
![image](https://user-images.githubusercontent.com/12371744/80545657-c13fa800-8968-11ea-81e8-ed0741737899.png)

Step 9: 
![image](https://user-images.githubusercontent.com/12371744/80545846-24c9d580-8969-11ea-9115-0a4e65b2e48b.png)

Step 10: 
![image](https://user-images.githubusercontent.com/12371744/80545862-2e533d80-8969-11ea-9fcf-b3430080b1c2.png)

Step 11:
![image](https://user-images.githubusercontent.com/12371744/80545890-3a3eff80-8969-11ea-808c-e4138332c60a.png)

Step 12: 
![image](https://user-images.githubusercontent.com/12371744/80545920-462ac180-8969-11ea-8560-efa5820c794d.png)

**Comment by joelhulen** [comment]
@periclesrocha I discovered that the Cosmos DB instance in your environment is missing 7/8ths of the records. I'm restoring now. I'll let you know when you can try again. Sorry about that.

**Comment by joelhulen** [comment]
@periclesrocha I've successfully updated Cosmos DB with all the required documents. Please try again and let me know.

**Comment by givenscj** [comment]
Closing.
