### ISSUE TITLE
L400 – Lab 6 Exercise 1 – Documentation

### ISSUE THREAD

**Issue by samurp** [solliancenet/azure-synapse-analytics-workshop-400#32]
This exercise seems to highlight that there is 4 basic things that need to be preformed. But when you log into the Notebook there is about 51 Cells that need to be run. Does running these Cells complete the items needed to complete this lab? I would suggest a better connection between what needs to be preformed and what we are doing in the lab exercise.

**Comment by ciprianjichici** [comment]
Will add a note in the lab material to clarify there are multiple cells per tasks. Also marking explicitly in the notebook where each of the tasks starts.
