### ISSUE TITLE
Lab3/Exercise2/task3

### ISSUE THREAD

**Issue by anshul82-ms** [solliancenet/azure-synapse-analytics-workshop-400#34]
The Setting of result Set cache as "On" is throwing a Syntax error. I am using the following command:
ALTER DATABASE [SQLPool01]
SET RESULT_SET_CACHING ON

**Comment by ciprianjichici** [comment]
Can you please specify at which step does this occur? Was not able to find 'On' anywhere.

**Comment by givenscj** [comment]
Just ran this lab and it worked as intended.
