### ISSUE TITLE
Lab 3/Exercise 2/Step 5/Step 2

### ISSUE THREAD

**Issue by anshul82-ms** [solliancenet/azure-synapse-analytics-workshop-400#36]
The query with clustered index column retrieved the results in 1 sec vs 15 secs took with the CCI option.

This is contrary to what is mentioned in the steps.

**Comment by ciprianjichici** [comment]
We are investigating the issue. We've seen in the past day a weird behavior where all queries on hash tables would get queued for no apparent reason (no other queries running on the pool).

**Comment by givenscj** [comment]
Closing as this was in the pre-release stages and seems to be fine now.
