### ISSUE TITLE
Day 2/Lab2/Exercise 2/Part1

### ISSUE THREAD

**Issue by anshul82-ms** [solliancenet/azure-synapse-analytics-workshop-400#37]
DBCC PDW_SHOWSPACEUSED('wwi_perf.Sale_Hash')

Running this commands throws the following error:
Failed to execute query. Error: Could not find object 'Sale_Hash' or you do not have permission.
Total execution time: 00:00:00.311

**Comment by givenscj** [comment]
This was a bug in the deployment back in April, works fine now.
