### ISSUE TITLE
Day 2/Lab2/Exercise 2/Part2

### ISSUE THREAD

**Issue by anshul82-ms** [solliancenet/azure-synapse-analytics-workshop-400#38]
While I was able to pick another table and run the transaction, it would be great to add bit more info on the use case here. It didn't ring a bell for me on how the table distribution impacts query performance just by executing the steps

**Comment by givenscj** [comment]
The title refers to the column store exercise, but your comment doesn't seem to match up to that exercise.  I believe we added a lot and move some things around since 4/30.
