### ISSUE TITLE
L400 - Day 3 - Lab 6 - Exercise 1

### ISSUE THREAD

**Issue by samurp** [solliancenet/azure-synapse-analytics-workshop-400#39]
When attempting to check if XGBoost is properly installed in the notebook, the following error is returned:

Exception : Not support to display this type of data: <class 'list'>
Traceback (most recent call last):
  File "<stdin>", line 891, in <lambda>
  File "<stdin>", line 718, in display
  File "<stdin>", line 671, in _convert
Exception: Not support to display this type of data: <class 'list'>

![image](https://user-images.githubusercontent.com/63663443/80766009-65188780-8b12-11ea-81f1-36462d592bb8.png)

**Comment by givenscj** [comment]
This was due to a missing requirements.txt file in the setup.  We have since updated, although you may run into indeterminate issues where you may need to re-upload the requirements file for the Spark Pool.
