### ISSUE TITLE
L400-Day 3-Lab 6-Exercise 1 Cell 7 line magic UsageError

### ISSUE THREAD

**Issue by samurp** [solliancenet/azure-synapse-analytics-workshop-400#40]
When attempting to run Cell 7 in the lab, I get the following error:

UsageError: %%spark is not a line magic.

![image](https://user-images.githubusercontent.com/63663443/80769307-c7758600-8b1a-11ea-9fa6-8bcb2bb418d8.png)

**Comment by samurp** [comment]
Potentially related to my previous issue, I think pip is failing to install potentially in Cell 3 and sparkmagic is not being installed in the Jupyter notebook for this to work. 
https://github.com/solliancenet/azure-synapse-analytics-workshop-400/issues/39

**Comment by givenscj** [comment]
This has been recently resolved by the synapse team, magics were disabled, but are now re-enabled.
