### ISSUE TITLE
Missing .\artifacts\environment-setup\labfiles\AzureCred.ps1

### ISSUE THREAD

**Issue by mboswell** [solliancenet/azure-synapse-analytics-workshop-400#52]
Please could you post an example of what this AzureCred.ps1 file should look like as it is missing from the repo. I'd like to get an idea of what I need to write to make the Repo work to create all of the environment and linked services.

**Comment by givenscj** [comment]
This file is used when running in the Spektra environment. If the file doesn't exist, it assumes you are running in cloud shell or on your local machine.  You should not need the AzureCred.ps1 file when running in your own environment.
